language: php
php:
  - '7.0'
deploy:
- provider: s3
  region: eu-west-1
  access_key_id: AKIAIN7RNJ425QQMKFXQ
  secret_access_key: &1
    secure: PvCyvmg67lFbuInMPttFLfgFIavJS5FDEluG4i4YwX0Xu0/KPfnHRN0UDc37gO/yWrWE5KS3Gs7yVooJ8sMt9SIiAFU+EHwegj8l4z98WTbxjeHl/OAQvALK1sj0vinbneSvNV9DAhqdrXf0QMBTy6nhTXrNrQXGVnBEFtfcxb7Aw9g4FossbMq+07qLrZpUv8qaJ0waweDft61HhfnWSKxY0nH7LDlAxRO8tIKrP7lHI0E0t6fdZ+BK+ePTMIWlRg0abV/xq5AGVMrznFK6/+56wdvMH0v9U+Liv9DJXS7XJ+fOZAo6ErDyZ4VZoxn2OSjE4oWANIn6CSzGq5Ky1XAqm/Fzm1n4T8WWIkyorVU7YLffjTdnQOkJ+pUXd4RSLU2jPwKj1UNPypqj+Qc10f5EH6lxWXuSfUjipB3EXHfmNkPsx1PYvDbrwnzmDca2NeNXuJZoxzEcli2wghkw4PJ7og4KIBZVJ+u4A+taoPPTkV5J0n5h1VB1Zy/tvxMpluR6txJThlEY5dhJZfRnQ8xxxF7A2gg86KUx2P8UuOYH2WiRl27GaXxWIAbsT7EAUOFkE9KH++DGjmEplvy/rcCyJV5N/Cla9HGNDJiGKfc7NuSGr0nW910lyGeuI+E8a7oWwd85ER8NxfOs6amqHbmyBAX8qhrhQc+DRGh/8P8=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: arnaud-P/aws-course-pokemon
  bucket: aws-bucket-arnaud-penin
  upload_dir: latest
- provider: codedeploy
  region: eu-west-1
  access_key_id: AKIAIN7RNJ425QQMKFXQ
  secret_access_key: *1
  bucket: aws-bucket-arnaud-penin
  key: latest/MyApp.zip
  bundle_type: zip
  application: aws-course-pokemon
  deployment_group: awsCoursePokemonGrp
  on: *2
before_deploy:
- zip MyApp -r *
- mkdir -p dpl_cd_upload
- mv MyApp.zip dpl_cd_upload/MyApp.zip
script:
- phpunit --coverage-clover --bootstrap test.php
