language: php
before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  provider: codedeploy
  access_key_id: AKIAIN7RNJ425QQMKFXQ
  secret_access_key:
    secure: AhaDs7AHFoQ5M+94/lF3RRbkhbOUrrdjn+pIOVAhTFzCfAdg9/I3qf9L5703gQQ0Lwtq4K9dFzzLpqyZB6AipvFlxZgIOF5+pL7AHNReym5rinpN4COMUcpD9Qfmszr7JcBRt+uYMcwdjzG4IcFAJP9XQ0Z+GsQ9/n6UlSLkwsIA7rhROjY5X6ELdmLmdnUlbi8Q6Kiyyd6SRJBcKJ7ab+dsr8uSQLo93Z8lkSvsjK6UA8D8St31CMOsKSKxlKfqHFIDkdLbS1sT9MytGOW2p2EYAoBpg1eXLPx0n1pkYtnStCQbGoxs8HJhkUJf6I+/SvB8MVpHKgbR2eedCEF3onqYacw+QK6t9oUPdYac1E5gj0qo0MX9BkzBtqtJcYV3u0/3o8AfQx2R1S45meTynK6ud745wXCTe3Y40f5LtnnB4j/cKsTwmewnBtI+zxF4B44dhxf9aeOh0F2HCEZPbSLKtVyxnv7VW4/rCXvJuuWRKSlr0blM+xXGHPsI5U4s4o8T+E1gE/9asUYvEDVkMzsPzLb9Z0WbMNZzKPHkDtLL3uWS3fZxe3bj+4IRgBkOAdgoabTrnEwFwsWDWZCzyIbXZbgn9kKLUFs9IyXucIH9bhNsSmXXyXA85xWIxMaKFtgBjVia/Ef/kwY7ZH+tNRXB+oyIi4eyQEPEn3tX1Yk=
  bucket: aws-bucket-arnaud-penin
  key: latest.zip
  bundle_type: zip
  application: aws-course-pokemon
  deployment_group: awsCoursePokemon
  on:
    repo: arnaud-P/aws-course-pokemon
  region: us-west-1
